--usuario

INSERT INTO CLIENTE (PAIS,APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('COSTA RICA','PEREZ', '1', 'ROBERTO', '093939393');
INSERT INTO CLIENTE (PAIS,APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('PANAMA','SANCHEZ', '2', 'RAUL', '093223333');
INSERT INTO CLIENTE (PAIS,APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('COSTA RICA','SANCHEZ PAZMINO', '11', 'PATRICIO', '092222');
INSERT INTO CLIENTE (PAIS,APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('PANAMA','SANCHEZ SALAZAR', '111', 'MAURICIO', '0933333');
INSERT INTO CLIENTE (PAIS,APELLIDOS, CEDULA, NOMBRE, TELEFONO) VALUES ('COSTA RICA','SANCHEZ SALAZAR', '1111', 'HORACIO', '0934555');

INSERT INTO CUENTA(ESTADO,NUMERO,TIPO,CLIENT_ID) VALUES('ACTIVA','10001212250','CREDITO',1);
INSERT INTO CUENTA(ESTADO,NUMERO,TIPO,CLIENT_ID) VALUES('INACTIVA','1002467513','CREDITO',3);
INSERT INTO CUENTA(ESTADO,NUMERO,TIPO,CLIENT_ID) VALUES('ACTIVA','873132130','CREDITO',5);